"""add app_releases and device_tokens tables

Revision ID: d3a2a0e40fc1
Revises: b325c7f28603
Create Date: 2026-10-02 15:44:49.059774

Hand-written rather than autogenerated: this database is shared with an unrelated project (a
separate Django app's tables live here too), and Alembic's autogenerate diffs against *all*
tables it can see, so the raw --autogenerate output included DROP TABLE statements for that
other project's tables (anything not in Mirror's own SQLModel metadata reads as "should be
removed"). This migration only touches the two tables Mirror actually owns.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3a2a0e40fc1'
down_revision: Union[str, None] = 'b325c7f28603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Two tables, one enum column each: the first table's create_table() auto-creates the
    # app_platform type as a side effect (plain sa.Enum, default create_type=True). The second
    # table's column uses the dialect-specific postgresql.ENUM with create_type=False instead of
    # a second plain sa.Enum - Alembic's op.create_table() forces checkfirst=False for any type it
    # auto-manages, so reusing the *same* sa.Enum object (even with create_type=False passed to
    # the generic class) still tries to CREATE TYPE again and fails with "already exists"; only
    # the dialect-specific ENUM class's create_type flag is actually honored at this DDL layer.
    op.create_table(
        'app_releases',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('platform', sa.Enum('android', 'ios', name='app_platform'), nullable=False),
        sa.Column('version_code', sa.Integer(), nullable=False),
        sa.Column('version_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column('download_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
        sa.Column('release_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_mandatory', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_app_releases_version_code'), 'app_releases', ['version_code'], unique=False)

    op.create_table(
        'device_tokens',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('token', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column('platform', postgresql.ENUM('android', 'ios', name='app_platform', create_type=False), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_device_tokens_token'), 'device_tokens', ['token'], unique=True)


def downgrade() -> None:
    op.drop_index(op.f('ix_device_tokens_token'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_app_releases_version_code'), table_name='app_releases')
    op.drop_table('app_releases')
    sa.Enum(name='app_platform').drop(op.get_bind(), checkfirst=True)
