"""initial schema

Revision ID: d936c162903a
Revises: 
Create Date: 2026-09-10 10:02:34.884108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd936c162903a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shade_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hex_color', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('category', sa.Enum('lipstick', 'foundation', 'powder', 'eyeshadow', 'blush', name='shade_category'), nullable=False),
    sa.Column('finish', sa.Enum('matte', 'glossy', 'shimmer', 'satin', name='shade_finish'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('account_type', sa.Enum('consumer', 'business', name='account_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('client_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tag', sa.Enum('self', 'client', name='client_tag'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_profiles_owner_user_id'), 'client_profiles', ['owner_user_id'], unique=False)
    op.create_table('enhance_usages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('billing_period', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
    sa.Column('render_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'billing_period', name='uq_enhance_usage_user_period')
    )
    op.create_index(op.f('ix_enhance_usages_billing_period'), 'enhance_usages', ['billing_period'], unique=False)
    op.create_index(op.f('ix_enhance_usages_user_id'), 'enhance_usages', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.Enum('solo', 'studio', name='subscription_plan'), nullable=False),
    sa.Column('status', sa.Enum('active', 'past_due', 'canceled', 'incomplete', name='subscription_status'), nullable=False),
    sa.Column('renews_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paystack_subscription_code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('makeup_looks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_profile_id', sa.Uuid(), nullable=False),
    sa.Column('source_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_profile_id'], ['client_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_makeup_looks_client_profile_id'), 'makeup_looks', ['client_profile_id'], unique=False)
    op.create_table('enhance_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('look_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'done', 'failed', name='enhance_job_status'), nullable=False),
    sa.Column('result_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['look_id'], ['makeup_looks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enhance_jobs_look_id'), 'enhance_jobs', ['look_id'], unique=False)
    op.create_index(op.f('ix_enhance_jobs_user_id'), 'enhance_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enhance_jobs_user_id'), table_name='enhance_jobs')
    op.drop_index(op.f('ix_enhance_jobs_look_id'), table_name='enhance_jobs')
    op.drop_table('enhance_jobs')
    op.drop_index(op.f('ix_makeup_looks_client_profile_id'), table_name='makeup_looks')
    op.drop_table('makeup_looks')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_enhance_usages_user_id'), table_name='enhance_usages')
    op.drop_index(op.f('ix_enhance_usages_billing_period'), table_name='enhance_usages')
    op.drop_table('enhance_usages')
    op.drop_index(op.f('ix_client_profiles_owner_user_id'), table_name='client_profiles')
    op.drop_table('client_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('shade_items')
    # ### end Alembic commands ###
